# Copyright 2018 ChemAxon Ltd.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file contains changes from https://github.com/mastnym and directly
# links the license file and the webservice config to the image from the 
# compose directory for easier change in the future.

version: '3'
services:
  jchem_webservices:
    build: .
    ports:
      - "8030:8080"
    image: chemaxon/jchem_webservices:latest
    volumes:
      - cxn_home:/usr/local/tomcat/.chemaxon/
      - ./license.cxl:/usr/local/tomcat/.chemaxon/license.cxl
      - ./ws-config.xml:/usr/local/tomcat/.chemaxon/ws-config.xml
    
volumes:
  cxn_home:
